export const PARSER_ALIASES = [
    { alias: "JUMBO S COLOR", caliberId: "jumbo-color" },
    { alias: "JUMBO E COLOR", caliberId: "jumbo-color" },
    { alias: "JUMBO I COLOR", caliberId: "jumbo-color" },
    { alias: "S COLOR", caliberId: "super-color" },
    { alias: "E COLOR", caliberId: "extra-color" },
    { alias: "I COLOR", caliberId: "primera-color" },
    { alias: "SB", caliberId: "super-blanco" },
    { alias: "SUPER BLANCO", caliberId: "super-blanco" },
    { alias: "SUPER", caliberId: "super-blanco" },
    { alias: "EXB", caliberId: "extra-blanco" },
    { alias: "EB", caliberId: "extra-blanco" },
    { alias: "EXTRA BLANCO", caliberId: "extra-blanco" },
    { alias: "EXTRA", caliberId: "extra-blanco" },
    { alias: "LB", caliberId: "primera-blanco" },
    { alias: "IB", caliberId: "primera-blanco" },
    { alias: "PB", caliberId: "primera-blanco" },
    { alias: "1B", caliberId: "primera-blanco" },
    { alias: "PRIMERA BLANCO", caliberId: "primera-blanco" },
    { alias: "PRIMERA", caliberId: "primera-blanco" },
    { alias: "LLB", caliberId: "segunda-blanco" },
    { alias: "IIB", caliberId: "segunda-blanco" },
    { alias: "2B", caliberId: "segunda-blanco" },
    { alias: "SEGUNDA BLANCO", caliberId: "segunda-blanco" },
    { alias: "SEGUNDA", caliberId: "segunda-blanco" },
    { alias: "JB", caliberId: "jumbo-blanco" },
    { alias: "JUMBO BLANCO", caliberId: "jumbo-blanco" },
    { alias: "JUMBO", caliberId: "jumbo-blanco" },
    { alias: "SC", caliberId: "super-color" },
    { alias: "SUPER COLOR", caliberId: "super-color" },
    { alias: "EXC", caliberId: "extra-color" },
    { alias: "EC", caliberId: "extra-color" },
    { alias: "EXTRA COLOR", caliberId: "extra-color" },
    { alias: "LC", caliberId: "primera-color" },
    { alias: "IC", caliberId: "primera-color" },
    { alias: "PC", caliberId: "primera-color" },
    { alias: "1C", caliberId: "primera-color" },
    { alias: "PRIMERA COLOR", caliberId: "primera-color" },
    { alias: "LLC", caliberId: "segunda-color" },
    { alias: "IIC", caliberId: "segunda-color" },
    { alias: "2C", caliberId: "segunda-color" },
    { alias: "SEGUNDA COLOR", caliberId: "segunda-color" },
    { alias: "JC", caliberId: "jumbo-color" },
    { alias: "JUMBO COLOR", caliberId: "jumbo-color" }
];
