import { z } from "zod";
export declare const purchaseLineSchema: z.ZodObject<{
    lineId: z.ZodString;
    caliberId: z.ZodString;
    caliberName: z.ZodString;
    category: z.ZodEnum<["blanco", "color"]>;
    unitPrice: z.ZodNumber;
    boxes: z.ZodNumber;
    unitsPerBox: z.ZodNumber;
    totalUnits: z.ZodNumber;
    subtotal: z.ZodNumber;
    parserConfidence: z.ZodOptional<z.ZodNumber>;
    parserRawLabel: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    caliberId?: string;
    category?: "color" | "blanco";
    lineId?: string;
    caliberName?: string;
    unitPrice?: number;
    boxes?: number;
    unitsPerBox?: number;
    totalUnits?: number;
    subtotal?: number;
    parserConfidence?: number;
    parserRawLabel?: string;
}, {
    caliberId?: string;
    category?: "color" | "blanco";
    lineId?: string;
    caliberName?: string;
    unitPrice?: number;
    boxes?: number;
    unitsPerBox?: number;
    totalUnits?: number;
    subtotal?: number;
    parserConfidence?: number;
    parserRawLabel?: string;
}>;
export declare const purchaseHeaderSchema: z.ZodEffects<z.ZodObject<{
    supplierId: z.ZodString;
    supplierName: z.ZodString;
    customSupplierName: z.ZodOptional<z.ZodString>;
    documentNumber: z.ZodString;
    purchaseDate: z.ZodString;
    responsibleName: z.ZodString;
    authorizerName: z.ZodString;
    deliveryMode: z.ZodEnum<["retiro", "despacho"]>;
    pickupLocationId: z.ZodOptional<z.ZodString>;
    pickupLocationLabel: z.ZodOptional<z.ZodString>;
    addressText: z.ZodString;
    paymentMethod: z.ZodString;
    notes: z.ZodDefault<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    notes?: string;
    supplierId?: string;
    supplierName?: string;
    customSupplierName?: string;
    documentNumber?: string;
    purchaseDate?: string;
    responsibleName?: string;
    authorizerName?: string;
    deliveryMode?: "retiro" | "despacho";
    pickupLocationId?: string;
    pickupLocationLabel?: string;
    addressText?: string;
    paymentMethod?: string;
}, {
    notes?: string;
    supplierId?: string;
    supplierName?: string;
    customSupplierName?: string;
    documentNumber?: string;
    purchaseDate?: string;
    responsibleName?: string;
    authorizerName?: string;
    deliveryMode?: "retiro" | "despacho";
    pickupLocationId?: string;
    pickupLocationLabel?: string;
    addressText?: string;
    paymentMethod?: string;
}>, {
    notes?: string;
    supplierId?: string;
    supplierName?: string;
    customSupplierName?: string;
    documentNumber?: string;
    purchaseDate?: string;
    responsibleName?: string;
    authorizerName?: string;
    deliveryMode?: "retiro" | "despacho";
    pickupLocationId?: string;
    pickupLocationLabel?: string;
    addressText?: string;
    paymentMethod?: string;
}, {
    notes?: string;
    supplierId?: string;
    supplierName?: string;
    customSupplierName?: string;
    documentNumber?: string;
    purchaseDate?: string;
    responsibleName?: string;
    authorizerName?: string;
    deliveryMode?: "retiro" | "despacho";
    pickupLocationId?: string;
    pickupLocationLabel?: string;
    addressText?: string;
    paymentMethod?: string;
}>;
export declare const purchasePayloadSchema: z.ZodObject<{
    header: z.ZodEffects<z.ZodObject<{
        supplierId: z.ZodString;
        supplierName: z.ZodString;
        customSupplierName: z.ZodOptional<z.ZodString>;
        documentNumber: z.ZodString;
        purchaseDate: z.ZodString;
        responsibleName: z.ZodString;
        authorizerName: z.ZodString;
        deliveryMode: z.ZodEnum<["retiro", "despacho"]>;
        pickupLocationId: z.ZodOptional<z.ZodString>;
        pickupLocationLabel: z.ZodOptional<z.ZodString>;
        addressText: z.ZodString;
        paymentMethod: z.ZodString;
        notes: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    }, "strip", z.ZodTypeAny, {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    }, {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    }>, {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    }, {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    }>;
    lines: z.ZodArray<z.ZodObject<{
        lineId: z.ZodString;
        caliberId: z.ZodString;
        caliberName: z.ZodString;
        category: z.ZodEnum<["blanco", "color"]>;
        unitPrice: z.ZodNumber;
        boxes: z.ZodNumber;
        unitsPerBox: z.ZodNumber;
        totalUnits: z.ZodNumber;
        subtotal: z.ZodNumber;
        parserConfidence: z.ZodOptional<z.ZodNumber>;
        parserRawLabel: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        caliberId?: string;
        category?: "color" | "blanco";
        lineId?: string;
        caliberName?: string;
        unitPrice?: number;
        boxes?: number;
        unitsPerBox?: number;
        totalUnits?: number;
        subtotal?: number;
        parserConfidence?: number;
        parserRawLabel?: string;
    }, {
        caliberId?: string;
        category?: "color" | "blanco";
        lineId?: string;
        caliberName?: string;
        unitPrice?: number;
        boxes?: number;
        unitsPerBox?: number;
        totalUnits?: number;
        subtotal?: number;
        parserConfidence?: number;
        parserRawLabel?: string;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    header?: {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    };
    lines?: {
        caliberId?: string;
        category?: "color" | "blanco";
        lineId?: string;
        caliberName?: string;
        unitPrice?: number;
        boxes?: number;
        unitsPerBox?: number;
        totalUnits?: number;
        subtotal?: number;
        parserConfidence?: number;
        parserRawLabel?: string;
    }[];
}, {
    header?: {
        notes?: string;
        supplierId?: string;
        supplierName?: string;
        customSupplierName?: string;
        documentNumber?: string;
        purchaseDate?: string;
        responsibleName?: string;
        authorizerName?: string;
        deliveryMode?: "retiro" | "despacho";
        pickupLocationId?: string;
        pickupLocationLabel?: string;
        addressText?: string;
        paymentMethod?: string;
    };
    lines?: {
        caliberId?: string;
        category?: "color" | "blanco";
        lineId?: string;
        caliberName?: string;
        unitPrice?: number;
        boxes?: number;
        unitsPerBox?: number;
        totalUnits?: number;
        subtotal?: number;
        parserConfidence?: number;
        parserRawLabel?: string;
    }[];
}>;
